// Generated by BetaScript Compiler
const __fs = require('fs');
const __runtime = {
  teriak: (...args) => console.log(...args),
  bisik: (msg) => process.stdout.write(String(msg)),
  dengerin: (msg) => require('readline-sync').question(msg),
  sebrapa: (arr) => arr?.length ?? 0,
  ape: (val) => typeof val,
  itungan: (val) => Number(val),
  omongan: (val) => String(val),
  kumpulin: (...items) => Array(...items),
  acak: () => Math.random(),
  tidur: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
  semua: (promises) => Promise.all(promises),
  balap: (promises) => Promise.race(promises)
};

class Anjing {
  constructor(nama: tulisan) {
    (this.nama = nama);
  }
  bersuara() {
    return "Guk guk!";
  }
}
let anjing = new Anjing("Buddy");
teriak(anjing.bersuara());
