import { IRModule, IRStatement, IRExpression, IRType, IRVariableDeclaration,
  IRFunctionDeclaration, IRClassDeclaration, IRInterfaceDeclaration,
  IRTypeAliasDeclaration, IREnumDeclaration, IRDecoratorApplication,
  IRIfStatement, IRWhileStatement, IRForStatement, IRForEachStatement,
  IRReturnStatement, IRThrowStatement, IRTryStatement, IRCatchClause,
  IRBreakStatement, IRContinueStatement, IRExpressionStatement,
  IRBlockStatement, IRMethodDeclaration, IRFieldDeclaration,
  IRConstructorDeclaration, IRClassMember, SourceSpan
} from "../ir/IR";
import { CodeGenerator } from "./CodeGenerator";

export class PythonGenerator extends CodeGenerator {
  name = "python";
  private decorators: Map<string, IRExpression[]> = new Map();

  generate(module: IRModule, options?: any): string {
    this.output = "";
    this.indent = 0;
    this.decorators = new Map();
    this.emitLine("# Generated by BetaScript Compiler");
    for (const stmt of module.body) this.emitStatement(stmt);
    return this.output;
  }

  protected emitType(type: IRType): string {
    if (!type) return "";
    switch (type.kind) {
      case "Primitive":
        const n = (type as any).name;
        switch (n) {
          case "number": return "float";
          case "string": return "str";
          case "boolean": return "bool";
          case "void": return "None";
          case "null": return "None";
          default: return "Any";
        }
      case "Array": return `list[${this.emitType((type as any).elementType)}]`;
      case "Union": return (type as any).types.map((t: IRType) => this.emitType(t)).join(" | ");
      case "Nullable": return `${this.emitType((type as any).type)} | None`;
      case "Named": {
        const name = (type as any).name;
        const args = (type as any).typeArguments;
        if (args && args.length > 0) {
          return `${name}[${args.map((t: IRType) => this.emitType(t)).join(", ")}]`;
        }
        return name;
      }
      default: return "Any";
    }
  }

  protected emitVariableDeclaration(stmt: IRVariableDeclaration) {
    const init = stmt.initializer ? ` = ${this.emitExpression(stmt.initializer)}` : "";
    this.emitLine(`${stmt.name}${init}`);
  }

  protected emitFunctionDeclaration(stmt: IRFunctionDeclaration) {
    const async = stmt.isAsync ? "async " : "";
    const params = stmt.parameters.map(p => {
      if ((p as any).defaultValue) return `${p.name} = ${this.emitExpression((p as any).defaultValue)}`;
      return p.name;
    }).join(", ");
    this.wrapBlock(() => {
      this.emitBlockBody(stmt.body);
    }, `${async}def ${stmt.name}(${params}):`);
  }

  protected emitClassDeclaration(stmt: IRClassDeclaration) {
    let head = "class " + stmt.name;
    if (stmt.superclass) head += `(${stmt.superclass})`;
    this.wrapBlock(() => {
      for (const m of stmt.members) this.emitClassMember(m);
    }, head + ":");
  }

  protected emitClassMember(member: IRClassMember) {
    switch (member.type) {
      case "MethodDeclaration":
        this.emitMethodDeclaration(member as IRMethodDeclaration);
        break;
      case "FieldDeclaration":
        this.emitFieldDeclaration(member as IRFieldDeclaration);
        break;
      case "ConstructorDeclaration":
        this.emitConstructorDeclaration(member as IRConstructorDeclaration);
        break;
    }
  }

  protected emitMethodDeclaration(method: IRMethodDeclaration) {
    const staticKw = method.isStatic ? "@staticmethod\n" : "";
    const asyncKw = (method as any).isAsync ? "async " : "";
    const params = method.parameters.map(p => {
      if ((p as any).defaultValue) return `${p.name} = ${this.emitExpression((p as any).defaultValue)}`;
      return p.name;
    }).join(", ");
    this.emitLine(`${staticKw}def ${method.name}(${params}):`);
  }

  protected emitFieldDeclaration(field: IRFieldDeclaration) {
    const init = field.initializer ? ` = ${this.emitExpression(field.initializer)}` : "";
    this.emitLine(`self.${field.name}${init}`);
  }

  protected emitConstructorDeclaration(ctor: IRConstructorDeclaration) {
    const params = ctor.parameters.map(p => {
      if ((p as any).defaultValue) return `${p.name} = ${this.emitExpression((p as any).defaultValue)}`;
      return p.name;
    }).join(", ");
    this.wrapBlock(() => {
      if (ctor.parameters.length > 0) {
        for (const p of ctor.parameters) {
          this.emitLine(`self.${p.name} = ${p.name}`);
        }
      }
      this.emitBlockBody(ctor.body);
    }, `def __init__(${params}):`);
  }

  protected emitIfStatement(stmt: IRIfStatement) {
    this.wrapBlock(() => this.emitBlockBody(stmt.consequent), `if ${this.emitExpression(stmt.test)}:`);
    if (stmt.alternate) {
      this.wrapBlock(() => this.emitBlockBody(stmt.alternate), "else:");
    }
  }

  protected emitWhileStatement(stmt: IRWhileStatement) {
    this.wrapBlock(() => this.emitBlockBody(stmt.body), `while ${this.emitExpression(stmt.test)}:`);
  }

  protected emitForStatement(stmt: IRForStatement) {
    const init = `${stmt.init.name} = ${stmt.init.initializer ? this.emitExpression(stmt.init.initializer) : "0"}`;
    this.wrapBlock(() => this.emitBlockBody(stmt.body), `for ${init} in range(${this.emitExpression(stmt.test)}):`);
  }

  protected emitForEachStatement(stmt: IRForEachStatement) {
    this.wrapBlock(() => this.emitBlockBody(stmt.body), `for ${stmt.variable} in ${this.emitExpression(stmt.iterable)}:`);
  }

  protected emitReturnStatement(stmt: IRReturnStatement) {
    if (stmt.argument) this.emitLine(`return ${this.emitExpression(stmt.argument)}`);
    else this.emitLine("return");
  }

  protected emitThrowStatement(stmt: IRThrowStatement) {
    this.emitLine(`raise ${this.emitExpression(stmt.argument)}`);
  }

  protected wrapBlock(body: () => void, opening: string, closing: string = "") {
    this.emitLine(opening);
    this.indent++;
    body();
    this.indent--;
    if (closing) this.emitLine(closing);
  }
}